// Region catalogue (generated by `uv run python -m elucidario.cartography.build`) and region auto-selection.
// Used at build time by MapView.astro. The client reads the same data from /maps/manifest.json.
import gen from './generated/regions.json';
import { makeProjection, type ProjSpec } from './proj';

export interface Region {
  id: string; name: string; kind: 'islands' | 'continent'; proj: ProjSpec;
  frame: [number, number, number, number]; aspect: number; plate: string; detail?: string; unit: number;
  inset?: string | null; labels?: string;
  relief?: Record<'s' | 'l', { src: string; w: number; h: number; z: number }>;
}
export const REGIONS = (gen as any).regions as Record<string, Region>;
export const VERSION = (gen as any).version as number;
export const ISLAND_REGIONS = ['madeira', 'porto-santo', 'desertas', 'selvagens'];

/** Island of a coordinate (mirrors geodata.island_of). */
export function islandOf(lon: number, lat: number): string {
  if (lat < 31) return 'selvagens';
  if (lat > 32.93) return 'porto-santo';
  if (lon > -16.6 && lat < 32.62) return 'desertas';
  return 'madeira';
}

const CONT: Record<string, string> = {
  Europe: 'europe', Africa: 'africa', 'South America': 'south-america', 'North America': 'north-america', Asia: 'asia',
  Oceania: 'oceania', 'Seven seas (open ocean)': 'africa',
};
const ALIAS: Record<string, string> = {
  Madeira: 'madeira', 'Porto Santo': 'porto-santo', Desertas: 'desertas', Selvagens: 'selvagens', Archipelago: 'archipelago', ...CONT,
};

export interface GeoLite { isl: string; cont: string | null; c: [number, number] | null }

/** Default region of one place, or null when it cannot be mapped. */
export function regionOfPlace(g: GeoLite | undefined): string | null {
  if (!g) return null;
  if (g.isl && g.isl !== 'none') return g.c ? islandOf(g.c[0], g.c[1]) : ALIAS[g.isl] ?? null;
  return (g.cont && CONT[g.cont]) || null;
}

/**
 * Region auto-selection: archipelago places win (one island → that island, several → the archipelago plate), otherwise the
 * continent with most places. `hint` (the `region` prop) is honoured when every archipelago place lies inside it.
 */
export function chooseRegion(regionsOfPlaces: (string | null)[], hint?: string, mode?: string): { region: string | null; abroad: Record<string, number> } {
  const isl = new Set<string>(), cont = new Map<string, number>();
  for (const r of regionsOfPlaces) {
    if (!r) continue;
    if (ISLAND_REGIONS.includes(r)) isl.add(r);
    else cont.set(r, (cont.get(r) ?? 0) + 1);
  }
  const h = hint ? ALIAS[hint] ?? hint.toLowerCase() : undefined;
  let region: string | null = null;
  if (mode === 'continent' && h && REGIONS[h]) region = h;
  else if (isl.size) {
    if (h && REGIONS[h] && REGIONS[h].kind === 'islands' && [...isl].every((i) => i === h)) region = h;
    else region = isl.size === 1 ? [...isl][0] : 'archipelago';
  } else if (cont.size) region = h && cont.has(h) ? h : [...cont.entries()].sort((a, b) => b[1] - a[1])[0][0];
  else if (h && REGIONS[h]) region = h;
  const abroad: Record<string, number> = {};
  if (region && REGIONS[region]?.kind === 'islands') for (const [k, v] of cont) abroad[k] = v;
  return { region, abroad };
}

/** Position of lon/lat inside a region frame, as fractions (0..1) of width and height. */
export function frameFraction(region: Region, lon: number, lat: number): [number, number] {
  const P = makeProjection(region.proj);
  const [x, y] = P.fwd(lon, lat);
  const [x0, y0, x1, y1] = region.frame;
  return [(x - x0) / (x1 - x0), (y - y0) / (y1 - y0)];
}
