# 15 worked examples: (title, pt, note, {lang: text})
X=[]
def ex(title,pt,note,**t): X.append(dict(title=title,pt=pt,note=note,t=t))
ex("Parish named after a saint, and the saint himself (uses 2 and 3)",
 "A freguesia de São Vicente tem por orago São Vicente, mártir. Em São Vicente a festa faz-se a 22 de Janeiro.",
 "*freguesia* already glossed earlier in the article. The parish gets the meaning; the saint as a person needs none.",
 en="The parish of São Vicente (‘St Vincent’) has St Vincent the Martyr as its patron saint. In São Vicente the feast is held on 22 January.",
 de="Die Gemeinde São Vicente (‚heiliger Vinzenz‘) hat den heiligen Märtyrer Vinzenz zum Patron. In São Vicente wird das Fest am 22. Januar gefeiert.",
 fr="La paroisse de São Vicente (« saint Vincent ») a pour patron saint Vincent, martyr. À São Vicente, la fête a lieu le 22 janvier.",
 it="La parrocchia di São Vicente (‘san Vincenzo’) ha per patrono san Vincenzo martire. A São Vicente la festa si celebra il 22 gennaio.",
 hu="São Vicente (’Szent Vince’) egyházközség védőszentje Szent Vince vértanú. São Vicentében az ünnepet január 22-én tartják.",
 nl="De parochie São Vicente (‘Sint-Vincentius’) heeft de heilige martelaar Vincentius als patroon. In São Vicente wordt het feest op 22 januari gevierd.")
ex("The source explains the name: no gloss",
 "Zargo deu a este sítio o nome de Câmara de Lobos, pelos muitos lobos marinhos que ali encontrou. Câmara de Lobos foi elevada a vila em 1835.",
 "The sentence itself explains *Câmara de Lobos*, so the name gets no gloss (core §7.4). *lobos marinhos* = monk seals; a termbase entry *lobo-marinho* is proposed (naming_latin.md §13.2).",
 en="Zargo gave this spot the name Câmara de Lobos because of the many monk seals he found there. Câmara de Lobos was raised to the status of a town in 1835.",
 de="Zargo gab diesem Ort den Namen Câmara de Lobos, wegen der vielen Mönchsrobben, die er dort antraf. Câmara de Lobos wurde 1835 zur Kleinstadt erhoben.",
 fr="Zargo donna à ce lieu le nom de Câmara de Lobos, à cause des nombreux phoques moines qu’il y trouva. Câmara de Lobos fut érigé en bourg en 1835.",
 it="Zargo diede a questo luogo il nome di Câmara de Lobos per le molte foche monache che vi trovò. Câmara de Lobos fu elevata a borgo nel 1835.",
 hu="Zargo a sok ott talált barátfókáról nevezte el ezt a helyet Câmara de Lobosnak. Câmara de Lobost 1835-ben mezővárosi rangra emelték.",
 nl="Zargo gaf deze plek de naam Câmara de Lobos, vanwege de vele monniksrobben die hij er aantrof. Câmara de Lobos werd in 1835 tot stadje verheven.")
ex("Chapel dedication (use 1) and a glossed town in one sentence",
 "Na Ribeira Brava há uma capela de Nossa Senhora da Piedade, fundada em 1600. A capela da Piedade foi reedificada em 1750.",
 "Two different names, one parenthesis each. The short source form *capela da Piedade* becomes the translated form.",
 en="In Ribeira Brava (‘wild river’) there is a chapel of Our Lady of Pity (*Nossa Senhora da Piedade*), founded in 1600. The chapel of Our Lady of Pity was rebuilt in 1750.",
 de="In Ribeira Brava (‚wilder Bach‘) steht eine Pietà-Kapelle (*Nossa Senhora da Piedade*), die 1600 gegründet wurde. Die Pietà-Kapelle wurde 1750 neu errichtet.",
 fr="À Ribeira Brava (« rivière sauvage ») se trouve une chapelle Notre-Dame-de-Pitié (*Nossa Senhora da Piedade*), fondée en 1600. La chapelle Notre-Dame-de-Pitié fut reconstruite en 1750.",
 it="A Ribeira Brava (‘torrente impetuoso’) c’è una cappella della Madonna della Pietà (*Nossa Senhora da Piedade*), fondata nel 1600. La cappella della Madonna della Pietà fu ricostruita nel 1750.",
 hu="Ribeira Bravában (’vad patak’) áll egy 1600-ban alapított Fájdalmas Anya-kápolna (*Nossa Senhora da Piedade*). A Fájdalmas Anya-kápolnát 1750-ben újjáépítették.",
 nl="In Ribeira Brava (‘wilde beek’) staat een Piëtakapel (*Nossa Senhora da Piedade*), gesticht in 1600. De Piëtakapel werd in 1750 herbouwd.")
ex("Book without a published translation (descriptive title)",
 "Diz Gaspar Frutuoso nas Saudades da Terra que a ilha estava coberta de arvoredo. As Saudades da Terra acrescentam que o fogo durou sete anos.",
 "Descriptive title in the language's title quotes; original in italics, as printed.",
 en="Gaspar Frutuoso says in ‘Longing for the Homeland’ (*Saudades da Terra*) that the island was covered with trees. ‘Longing for the Homeland’ adds that the fire lasted seven years.",
 de="Gaspar Frutuoso berichtet in „Sehnsucht nach der Heimat“ (*Saudades da Terra*), die Insel sei mit Wald bedeckt gewesen. „Sehnsucht nach der Heimat“ fügt hinzu, dass das Feuer sieben Jahre dauerte.",
 fr="Gaspar Frutuoso dit dans « Nostalgie de la terre natale » (*Saudades da Terra*) que l’île était couverte d’arbres. « Nostalgie de la terre natale » ajoute que le feu dura sept ans.",
 it="Gaspar Frutuoso dice in ‘Nostalgia della terra natia’ (*Saudades da Terra*) che l’isola era coperta di alberi. ‘Nostalgia della terra natia’ aggiunge che il fuoco durò sette anni.",
 hu="Gaspar Frutuoso a „Vágyódás a szülőföld után” (*Saudades da Terra*) című művében azt írja, hogy a szigetet erdő borította. A „Vágyódás a szülőföld után” hozzáteszi, hogy a tűz hét évig tartott.",
 nl="Gaspar Frutuoso zegt in ‘Heimwee naar het vaderland’ (*Saudades da Terra*) dat het eiland met bos bedekt was. ‘Heimwee naar het vaderland’ voegt eraan toe dat het vuur zeven jaar duurde.")
ex("Book with an established translation",
 "Camões refere-se à Madeira no canto V dos Lusíadas. Os Lusíadas foram publicados em 1572.",
 "Established title in italics. The parenthesis gives the original once.",
 en="Camões mentions Madeira in Canto V of *The Lusiads* (*Os Lusíadas*). *The Lusiads* was published in 1572.",
 de="Camões erwähnt Madeira im fünften Gesang der *Lusiaden* (*Os Lusíadas*). *Die Lusiaden* erschienen 1572.",
 fr="Camões évoque Madère au chant V des *Lusiades* (*Os Lusíadas*). *Les Lusiades* parurent en 1572.",
 it="Camões ricorda Madera nel canto V dei *Lusiadi* (*Os Lusíadas*). *I Lusiadi* furono pubblicati nel 1572.",
 hu="Camões *A lusiadák* (*Os Lusíadas*) V. énekében említi Madeirát. *A lusiadák* 1572-ben jelent meg.",
 nl="Camões noemt Madeira in de vijfde zang van *De Lusiaden* (*Os Lusíadas*). *De Lusiaden* verscheen in 1572.")
ex("Periodical: masthead kept, meaning glossed",
 "O Heraldo da Madeira de 18 de Novembro de 1913 inseriu um artigo sobre o assunto. O mesmo Heraldo publicou depois a resposta.",
 "Italian sets mastheads in caporali.",
 en="The *Heraldo da Madeira* (‘Madeira Herald’) of 18 November 1913 carried an article on the subject. The same *Heraldo* later published the reply.",
 de="Der *Heraldo da Madeira* (‚Herold von Madeira‘) vom 18. November 1913 brachte einen Artikel zu diesem Thema. Derselbe *Heraldo* veröffentlichte später die Antwort.",
 fr="Le *Heraldo da Madeira* (« Le Héraut de Madère ») du 18 novembre 1913 publia un article sur la question. Le même *Heraldo* fit paraître ensuite la réponse.",
 it="L’«Heraldo da Madeira» (‘L’Araldo di Madera’) del 18 novembre 1913 pubblicò un articolo sull’argomento. Lo stesso «Heraldo» diede poi alle stampe la risposta.",
 hu="A *Heraldo da Madeira* (’Madeirai Hírnök’) 1913. november 18-i száma cikket közölt a kérdésről. Ugyanez a *Heraldo* később a választ is kinyomtatta.",
 nl="De *Heraldo da Madeira* (‘De Heraut van Madeira’) van 18 november 1913 bracht een artikel over de kwestie. Dezelfde *Heraldo* publiceerde later het antwoord.")
ex("Historical figure with an established name (no parenthesis)",
 "O Infante D. Henrique mandou povoar a ilha. O Infante concedeu a capitania a Zargo.",
 "From kb/historical_figures.yaml. *capitania* per termbase.",
 en="Henry the Navigator ordered the island to be settled. The Infante granted the captaincy to Zargo.",
 de="Heinrich der Seefahrer ließ die Insel besiedeln. Der Infant verlieh Zargo das Kapitanat.",
 fr="Henri le Navigateur fit peupler l’île. L’Infant accorda la capitainerie à Zargo.",
 it="Enrico il Navigatore fece popolare l’isola. L’Infante concesse la capitania a Zargo.",
 hu="Tengerész Henrik elrendelte a sziget benépesítését. Az infáns Zargónak adományozta a kapitányságot.",
 nl="Hendrik de Zeevaarder liet het eiland bevolken. De infant schonk het kapiteinschap aan Zargo.")
ex("Honorifics and a noble title",
 "O Dr. João da Câmara Leme, conde do Canavial, e D. Isabel de Abreu assistiram à cerimónia. O conde discursou.",
 "The territorial designation (*Canavial*) is never glossed.",
 en="Dr João da Câmara Leme, Count of Canavial, and Dona Isabel de Abreu attended the ceremony. The Count gave a speech.",
 de="Dr. João da Câmara Leme, Graf von Canavial, und Dona Isabel de Abreu wohnten der Feier bei. Der Graf hielt eine Rede.",
 fr="Le docteur João da Câmara Leme, comte de Canavial, et dona Isabel de Abreu assistèrent à la cérémonie. Le comte prononça un discours.",
 it="Il dottor João da Câmara Leme, conte di Canavial, e dona Isabel de Abreu assistettero alla cerimonia. Il conte tenne un discorso.",
 hu="Dr. João da Câmara Leme, Canavial grófja, és Dona Isabel de Abreu is jelen volt a szertartáson. A gróf beszédet mondott.",
 nl="Dr. João da Câmara Leme, graaf van Canavial, en Dona Isabel de Abreu woonden de plechtigheid bij. De graaf hield een toespraak.")
ex("Clergy",
 "O cónego Jerónimo Dias Leite e Frei Pedro de Bettencourt acompanhavam o padre Manuel Álvares.",
 "",
 en="Canon Jerónimo Dias Leite and Friar Pedro de Bettencourt accompanied Father Manuel Álvares.",
 de="Domherr Jerónimo Dias Leite und Frei Pedro de Bettencourt begleiteten Padre Manuel Álvares.",
 fr="Le chanoine Jerónimo Dias Leite et frère Pedro de Bettencourt accompagnaient le père Manuel Álvares.",
 it="Il canonico Jerónimo Dias Leite e fra Pedro de Bettencourt accompagnavano padre Manuel Álvares.",
 hu="Jerónimo Dias Leite kanonok és Frei Pedro de Bettencourt kísérte Manuel Álvares atyát.",
 nl="Kanunnik Jerónimo Dias Leite en frei Pedro de Bettencourt vergezelden padre Manuel Álvares.")
ex("Institution and an institution named after a saint",
 "A Santa Casa da Misericórdia do Funchal administrava o Hospital de Santa Isabel. A Misericórdia recebia legados.",
 "Termbase gives the institution and its short form; the hospital's generic and dedication are translated (naming_latin.md §13.3, item 7).",
 en="The Holy House of Mercy (*Santa Casa da Misericórdia*) of Funchal ran St Elizabeth’s Hospital (*Hospital de Santa Isabel*). The Misericórdia received bequests.",
 de="Das Heilige Haus der Barmherzigkeit (*Santa Casa da Misericórdia*) von Funchal verwaltete das St.-Elisabeth-Hospital (*Hospital de Santa Isabel*). Die Misericórdia erhielt Vermächtnisse.",
 fr="La Sainte Maison de la Miséricorde (*Santa Casa da Misericórdia*) de Funchal administrait l’hôpital Sainte-Élisabeth (*Hospital de Santa Isabel*). La Misericórdia recevait des legs.",
 it="La Santa Casa della Misericordia (*Santa Casa da Misericórdia*) di Funchal amministrava l’ospedale di Santa Elisabetta (*Hospital de Santa Isabel*). La Misericordia riceveva lasciti.",
 hu="A funchali Irgalmasság Szent Háza (*Santa Casa da Misericórdia*) tartotta fenn a Szent Erzsébet-kórházat (*Hospital de Santa Isabel*). A Misericórdia hagyatékokat kapott.",
 nl="Het Heilig Huis van Barmhartigheid (*Santa Casa da Misericórdia*) van Funchal beheerde het Sint-Elisabethziekenhuis (*Hospital de Santa Isabel*). De Misericórdia ontving legaten.")
ex("Fort named after a saint: São Tiago is James the Less",
 "Os navios fundearam defronte da Fortaleza de São Tiago. A fortaleza de São Tiago respondeu com artilharia.",
 "Secular building: generic translated, Portuguese specific kept, saint glossed (Funchal patron = the Less).",
 en="The ships anchored off the Fortress of São Tiago (‘St James the Less’). The São Tiago fortress returned fire.",
 de="Die Schiffe ankerten vor der Festung São Tiago (‚heiliger Jakobus der Jüngere‘). Die Festung São Tiago erwiderte das Feuer.",
 fr="Les navires mouillèrent devant la forteresse de São Tiago (« saint Jacques le Mineur »). La forteresse de São Tiago riposta au canon.",
 it="Le navi gettarono l’ancora davanti alla fortezza di São Tiago (‘san Giacomo il Minore’). La fortezza di São Tiago rispose con l’artiglieria.",
 hu="A hajók a São Tiago-erőd (’ifjabb Szent Jakab’) előtt vetettek horgonyt. A São Tiago-erőd ágyútűzzel válaszolt.",
 nl="De schepen gingen voor anker voor het fort São Tiago (‘Sint-Jakobus de Mindere’). Het fort São Tiago beantwoordde het vuur.")
ex("Street name",
 "Morava na Rua dos Ferreiros, junto à igreja do Colégio. A Rua dos Ferreiros era então muito estreita.",
 "",
 en="He lived in Rua dos Ferreiros (‘blacksmiths' street’), next to the Colégio church. Rua dos Ferreiros was very narrow at the time.",
 de="Er wohnte in der Rua dos Ferreiros (‚Schmiedestraße‘) neben der Colégio-Kirche. Die Rua dos Ferreiros war damals sehr eng.",
 fr="Il habitait la Rua dos Ferreiros (« rue des Forgerons »), près de l’église du Colégio. La Rua dos Ferreiros était alors très étroite.",
 it="Abitava in Rua dos Ferreiros (‘via dei fabbri’), accanto alla chiesa del Colégio. La Rua dos Ferreiros era allora molto stretta.",
 hu="A Rua dos Ferreirosban (’kovácsok utcája’) lakott, a Colégio-templom mellett. A Rua dos Ferreiros akkoriban igen keskeny volt.",
 nl="Hij woonde in de Rua dos Ferreiros (‘smedenstraat’), naast de Colégiokerk. De Rua dos Ferreiros was toen erg smal.")
ex("Marian feast (use 3) and the parish of the same name (use 2)",
 "A festa de Nossa Senhora do Monte, a 15 de Agosto, atrai romeiros de toda a ilha. A romaria do Monte é a maior da Madeira.",
 "Italian leaves *Monte* without a gloss (identical word).",
 en="The feast of Our Lady of the Mount (*Nossa Senhora do Monte*) on 15 August draws pilgrims from all over the island. The pilgrimage to Monte (‘hill’) is the largest in Madeira.",
 de="Das Fest Unserer Lieben Frau vom Berge (*Nossa Senhora do Monte*) am 15. August zieht Pilger von der ganzen Insel an. Die Wallfahrt nach Monte (‚Berg‘) ist die größte auf Madeira.",
 fr="La fête de Notre-Dame du Mont (*Nossa Senhora do Monte*), le 15 août, attire des pèlerins de toute l’île. Le pèlerinage de Monte (« mont ») est le plus important de Madère.",
 it="La festa della Madonna del Monte (*Nossa Senhora do Monte*), il 15 agosto, richiama pellegrini da tutta l’isola. Il pellegrinaggio a Monte è il più grande di Madera.",
 hu="A Monte-i Szűzanya (*Nossa Senhora do Monte*) augusztus 15-i ünnepére az egész szigetről érkeznek zarándokok. A Montéba (’hegy’) tartó búcsú Madeira legnagyobb búcsúja.",
 nl="Het feest van Onze-Lieve-Vrouw van de Berg (*Nossa Senhora do Monte*) op 15 augustus trekt pelgrims van het hele eiland. De bedevaart naar Monte (‘berg’) is de grootste van Madeira.")
ex("Grammar of place names (prepositions, cases, suffixes)",
 "Os moradores do Porto Santo passaram a Machico. Em Machico receberam terras.",
 "Italian leaves *Porto Santo* without a gloss (transparent).",
 en="The inhabitants of Porto Santo (‘holy harbour’) moved to Machico. In Machico they received land.",
 de="Die Bewohner von Porto Santo (‚Heiliger Hafen‘) zogen nach Machico. In Machico erhielten sie Land.",
 fr="Les habitants de Porto Santo (« port saint ») passèrent à Machico. À Machico, ils reçurent des terres.",
 it="Gli abitanti di Porto Santo si trasferirono a Machico. A Machico ricevettero terre.",
 hu="Porto Santo (’szent kikötő’) lakói Machicóba költöztek. Machicóban földet kaptak.",
 nl="De bewoners van Porto Santo (‘heilige haven’) trokken naar Machico. In Machico kregen zij land.")
ex("Island groups: exonym in some languages, gloss in others",
 "As Desertas e as Selvagens pertencem ao distrito do Funchal. Nas Desertas não há habitantes.",
 "en and it have exonyms for the Selvagens; hu has one for the Desertas.",
 en="The Desertas (‘deserted islands’) and the Savage Islands (*Selvagens*) belong to the district of Funchal. There are no inhabitants on the Desertas.",
 de="Die Desertas (‚verlassene Inseln‘) und die Selvagens (‚wilde Inseln‘) gehören zum Distrikt Funchal. Auf den Desertas gibt es keine Einwohner.",
 fr="Les îles Desertas (« îles désertes ») et les îles Selvagens (« îles sauvages ») appartiennent au district de Funchal. Les Desertas n’ont pas d’habitants.",
 it="Le Desertas (‘isole deserte’) e le isole Selvagge (*Selvagens*) appartengono al distretto di Funchal. Le Desertas sono disabitate.",
 hu="A Kopár-szigetek (*Desertas*) és a Selvagens-szigetek (’vad szigetek’) Funchal kerületéhez tartoznak. A Kopár-szigeteken nincsenek lakosok.",
 nl="De Desertas (‘verlaten eilanden’) en de Selvagens (‘wilde eilanden’) behoren tot het district Funchal. Op de Desertas wonen geen mensen.")
