# Descriptive toponyms: (pt, freq(articles), class, note, en, de, fr, it, hu, nl)
# Meaning only (no quotes); the build adds each language's gloss marks. "" = no gloss in that language.
# A value starting with "=" is an established exonym that REPLACES the Portuguese name (original goes in parentheses).
T = [
("Porto Santo",421,"island","", "holy harbour","Heiliger Hafen","port saint","","szent kikötő","heilige haven"),
("Câmara de Lobos",127,"parish/town","*lobos* = *lobos-marinhos*, monk seals; the source itself tells the story in several articles (then no gloss).", "seals' den","Robbenhöhle","repaire des phoques","tana delle foche","fókák barlangja","robbenhol"),
("Santa Cruz",125,"parish/town","Toponym; the parish church is São Salvador.", "Holy Cross","Heiliges Kreuz","Sainte-Croix","Santa Croce","Szent Kereszt","Heilig Kruis"),
("Ponta do Sol",122,"parish/town","", "point of the sun","Sonnenspitze","pointe du Soleil","punta del sole","Nap-fok","zonnekaap"),
("Calheta",109,"parish/town","The source explains it in the parish article (no gloss there).", "small cove","kleine Bucht","petite anse","caletta","kis öböl","kleine inham"),
("Monte",107,"parish","", "hill","Berg","mont","","hegy","berg"),
("Porto Moniz",96,"parish/town","Owner example; *Moniz* is a surname.", "Moniz's harbour","Hafen des Moniz","port de Moniz","porto di Moniz","Moniz kikötője","haven van Moniz"),
("Ribeira Brava",95,"parish/town","Owner example.", "wild river","wilder Bach","rivière sauvage","torrente impetuoso","vad patak","wilde beek"),
("Santo António",81,"parish (Funchal)","Hagiotoponym.", "St Anthony","heiliger Antonius","saint Antoine","sant'Antonio","Szent Antal","Sint-Antonius"),
("Caniço",75,"parish","The source explains it (reed, *Phragmites*).", "reed","Schilfrohr","roseau","canna palustre","nád","riet"),
("São Vicente",71,"parish/town","Hagiotoponym; homonym trap (§9 of naming_latin.md).", "St Vincent","heiliger Vinzenz","saint Vincent","san Vincenzo","Szent Vince","Sint-Vincentius"),
("Porto da Cruz",68,"parish","", "harbour of the cross","Hafen des Kreuzes","port de la Croix","porto della croce","a kereszt kikötője","haven van het kruis"),
("Ponta de São Lourenço",67,"cape","hu Wikipedia uses the exonym *Szent Lőrinc-félsziget*; see naming_hu.md.", "St Lawrence Point","Sankt-Laurentius-Spitze","pointe Saint-Laurent","punta di San Lorenzo","Szent Lőrinc-fok","Sint-Laurentiuskaap"),
("Desertas",62,"islands","hu: established exonym *Kopár-szigetek* (Wikipedia, Wikidata Q27923).", "deserted islands","verlassene Inseln","îles désertes","isole deserte","=a Kopár-szigetek","verlaten eilanden"),
("São Martinho",61,"parish (Funchal)","Hagiotoponym.", "St Martin","heiliger Martin","saint Martin","san Martino","Szent Márton","Sint-Maarten"),
("Curral das Freiras",52,"parish","Owner example; land of the Santa Clara nuns.", "nuns' fold","Pferch der Nonnen","enclos des religieuses","recinto delle monache","apácák karámja","kraal van de nonnen"),
("Ponta do Pargo",49,"parish","*pargo* = red porgy (*Pagrus pagrus*).", "sea bream point","Meerbrassenspitze","pointe du Pagre","punta del pagro","tengerikeszeg-fok","zeebrasemkaap"),
("Paul da Serra",48,"plateau","", "upland marsh","Bergsumpf","marais de la montagne","palude montana","hegyi mocsár","bergmoeras"),
("Santa Maria Maior",48,"parish (Funchal)","Hagiotoponym.", "St Mary Major","heilige Maria","Sainte-Marie-Majeure","Santa Maria Maggiore","Szent Mária","Sint-Maria"),
("Santana",48,"parish/town","From *Sant'Ana*.", "St Anne","heilige Anna","sainte Anne","sant'Anna","Szent Anna","Sint-Anna"),
("Campanário",46,"parish","", "bell tower","Glockenturm","clocher","campanile","harangtorony","klokkentoren"),
("Arco da Calheta",43,"parish","*arco* = the arc-shaped amphitheatre of land.", "arc of Calheta","Bogen von Calheta","arc de Calheta","arco di Calheta","calhetai ív","boog van Calheta"),
("Faial",43,"parish","The source explains it: *faia*, *Myrica faya*.", "faya grove","Gagelbaumhain","bois de fayas","bosco di faia","fayaliget","fayabos"),
("Selvagens",42,"islands","en *the Savage Islands* and it *le isole Selvagge* are established exonyms (Wikidata Q27088).", "=the Savage Islands","wilde Inseln","îles sauvages","=le isole Selvagge","vad szigetek","wilde eilanden"),
("Ribeira de Santa Luzia",41,"stream (Funchal)","", "St Lucy's stream","Bach der heiligen Lucia","torrent Sainte-Lucie","torrente di Santa Lucia","Szent Luca-patak","Sint-Luciabeek"),
("São Jorge",40,"parish","Hagiotoponym.", "St George","heiliger Georg","saint Georges","san Giorgio","Szent György","Sint-Joris"),
("Ponta Delgada",39,"parish","Also a city on São Miguel (Azores): same gloss.", "slender point","schmale Spitze","pointe effilée","punta sottile","keskeny fok","smalle kaap"),
("São Roque",36,"parish (Funchal)","Hagiotoponym.", "St Roch","heiliger Rochus","saint Roch","san Rocco","Szent Rókus","Sint-Rochus"),
("São Pedro",36,"parish (Funchal)","Hagiotoponym.", "St Peter","heiliger Petrus","saint Pierre","san Pietro","Szent Péter","Sint-Pieter"),
("Caniçal",35,"parish","", "reed bed","Röhricht","roselière","canneto","nádas","rietveld"),
("São Gonçalo",35,"parish (Funchal)","Hagiotoponym.", "St Gonçalo","heiliger Gonçalo","saint Gonzalve","san Gonsalvo","Szent Gonçalo","Sint-Gonçalo"),
("Estreito de Câmara de Lobos",34,"parish","*estreito* here = a narrow neck of land between ravines (not a sea strait).", "the narrows of Câmara de Lobos","Enge von Câmara de Lobos","étroit de Câmara de Lobos","stretta di Câmara de Lobos","Câmara de Lobos-i szoros","engte van Câmara de Lobos"),
("Ribeira de João Gomes",31,"stream (Funchal)","", "João Gomes's stream","Bach des João Gomes","torrent de João Gomes","torrente di João Gomes","João Gomes patakja","beek van João Gomes"),
("Estreito da Calheta",31,"parish","See Estreito de Câmara de Lobos.", "the narrows of Calheta","Enge von Calheta","étroit de Calheta","stretta di Calheta","calhetai szoros","engte van Calheta"),
("Paul do Mar",30,"parish","Owner example.", "marsh by the sea","Sumpf am Meer","marais de la mer","palude sul mare","tengerparti mocsár","moeras aan zee"),
("Boaventura",29,"parish","Owner example; the source says the origin of the name is unknown: give the literal meaning only.", "good fortune","gutes Glück","bonne fortune","buona ventura","jó szerencse","goed geluk"),
("Seixal",29,"parish","*seixo* = pebble.", "pebble shore","Kiesstrand","grève de galets","greto di ciottoli","kavicsos part","kiezelstrand"),
("Ribeiro Frio",27,"locality","", "cold brook","kalter Bach","ruisseau froid","ruscello freddo","hideg patak","koude beek"),
("Ribeira dos Socorridos",26,"stream","", "stream of the rescued","Bach der Geretteten","torrent des Secourus","torrente dei salvati","a megmentettek patakja","beek van de geredden"),
("Ribeira da Janela",25,"parish/stream","", "window stream","Fensterbach","torrent de la Fenêtre","torrente della finestra","ablak-patak","vensterbeek"),
("Madalena do Mar",25,"parish","Hagiotoponym (Mary Magdalene).", "Magdalene by the sea","Magdalena am Meer","Madeleine-de-la-Mer","Maddalena sul mare","tengerparti Magdolna","Magdalena aan zee"),
("Deserta Grande",24,"island","", "great deserted island","große verlassene Insel","Grande Déserte","grande deserta","nagy kopár sziget","groot verlaten eiland"),
("Pico Ruivo",24,"peak","", "russet peak","rötlicher Gipfel","pic roux","picco rossiccio","vöröses csúcs","rossige top"),
("Pontinha",24,"point/quay (Funchal)","", "little point","kleine Spitze","petite pointe","puntina","kis fok","kleine kaap"),
("Serra de Água",24,"parish","The source explains it (water-driven sawmills).", "water sawmill","Wassersäge","scierie à eau","segheria ad acqua","vízifűrész","watergedreven zaagmolen"),
("Fajã da Ovelha",23,"parish","Owner example; *fajã* = coastal flat below a cliff.", "the ewe's flat","Ebene des Mutterschafs","replat de la brebis","pianoro della pecora","a juh partsíkja","vlakte van de ooi"),
("Santo António da Serra",22,"parish","Hagiotoponym.", "St Anthony of the uplands","heiliger Antonius im Bergland","saint Antoine de la montagne","sant'Antonio della montagna","hegyvidéki Szent Antal","Sint-Antonius van het bergland"),
("Ponta da Cruz",22,"cape (Funchal)","", "point of the cross","Kreuzspitze","pointe de la Croix","punta della croce","kereszt-fok","kaap van het kruis"),
("Santa Luzia",21,"parish (Funchal)","Hagiotoponym.", "St Lucy","heilige Lucia","sainte Lucie","santa Lucia","Szent Luca","Sint-Lucia"),
("Tabua",21,"parish","The source explains it (the *tábua* plant, bulrush).", "bulrush","Rohrkolben","massette","tifa","gyékény","lisdodde"),
("Achadas da Cruz",19,"parish","*achada* = plateau.", "plateaus of the cross","Hochflächen des Kreuzes","replats de la Croix","pianori della croce","a kereszt fennsíkjai","hoogvlakten van het kruis"),
("Arco de São Jorge",18,"parish","", "arc of São Jorge","Bogen von São Jorge","arc de São Jorge","arco di São Jorge","São Jorge-i ív","boog van São Jorge"),
("Santo da Serra",17,"parish","Short for Santo António da Serra.", "the saint of the uplands","der Heilige im Bergland","le saint de la montagne","il santo della montagna","a hegyvidéki szent","de heilige van het bergland"),
("Praia Formosa",17,"beach","", "beautiful beach","schöner Strand","belle plage","spiaggia bella","szép strand","mooi strand"),
("Ponta da Oliveira",17,"cape","", "olive-tree point","Ölbaumspitze","pointe de l'Olivier","punta dell'ulivo","olajfa-fok","olijfboomkaap"),
("Jardim do Mar",17,"parish","", "garden by the sea","Garten am Meer","jardin de la mer","giardino sul mare","tengerparti kert","tuin aan zee"),
("Terreiro da Luta",17,"locality","", "ground of the fight","Kampfplatz","esplanade de la Lutte","spiazzo della lotta","a küzdelem tere","strijdplein"),
("Pico do Areeiro (Arieiro)",16,"peak","", "sand-pit peak","Sandgrubengipfel","pic de la Sablière","picco del sabbione","homokbánya-csúcs","zandgroeftop"),
("Rua Direita",16,"street (Funchal)","Odonym: generic kept in the name (core §7.3).", "straight street","gerade Straße","rue droite","via diritta","egyenes utca","rechte straat"),
("Penha de Águia",15,"peak","", "eagle crag","Adlerfels","rocher de l'Aigle","rupe dell'aquila","sas-szikla","adelaarsrots"),
("Rua dos Ferreiros",15,"street (Funchal)","", "blacksmiths' street","Schmiedestraße","rue des Forgerons","via dei fabbri","kovácsok utcája","smedenstraat"),
("Campo da Barca",15,"square (Funchal)","", "boat field","Bootsplatz","champ de la Barque","campo della barca","csónak-tér","bootveld"),
("Ilhéu Chão",15,"islet (Desertas)","", "flat islet","flache Felseninsel","îlot plat","isolotto piatto","lapos sziget","plat eilandje"),
("Ilhéu de Baixo",14,"islet (Porto Santo)","", "lower islet","untere Felseninsel","îlot d'en bas","isolotto di sotto","alsó sziget","onderste eilandje"),
("Quinta Grande",14,"parish","*quinta* = country estate.", "large estate","großes Landgut","grand domaine","grande tenuta","nagy birtok","groot landgoed"),
("Jardim da Serra",13,"locality","", "upland garden","Garten im Bergland","jardin de la montagne","giardino della montagna","hegyi kert","tuin in het bergland"),
("Quinta Vigia",13,"estate (Funchal)","", "lookout estate","Landgut Ausguck","domaine de la Vigie","tenuta della vedetta","őrhely-birtok","landgoed de Uitkijk"),
("Ilhéu de Cima",13,"islet (Porto Santo)","", "upper islet","obere Felseninsel","îlot d'en haut","isolotto di sopra","felső sziget","bovenste eilandje"),
("Ribeiro Seco",12,"stream","", "dry brook","trockener Bach","ruisseau sec","ruscello secco","száraz patak","droge beek"),
("Ilhéu de Fora",12,"islet","", "outer islet","äußere Felseninsel","îlot du large","isolotto di fuori","külső sziget","buitenste eilandje"),
("Selvagem Grande",11,"island","", "great wild island","große wilde Insel","Grande Sauvage","grande selvaggia","nagy vad sziget","groot wild eiland"),
("Fajã dos Padres",11,"locality","Named after the Jesuit fathers (the source says so; then no gloss).", "the priests' flat","Ebene der Patres","replat des Pères","pianoro dei padri","a papok partsíkja","vlakte van de paters"),
("Lugar de Baixo",11,"locality","", "lower place","unterer Ort","lieu d'en bas","luogo di sotto","alsó hely","onderste plaats"),
("Rua da Alfândega",11,"street (Funchal)","", "customs-house street","Zollhausstraße","rue de la Douane","via della dogana","vámház utca","douanestraat"),
("Largo do Pelourinho",11,"square (Funchal)","", "pillory square","Prangerplatz","place du Pilori","largo della gogna","pellengér tér","schandpaalplein"),
("Prazeres",10,"parish","From *Nossa Senhora dos Prazeres*.", "joys","Freuden","joies","gioie","örömök","vreugden"),
("Pico do Castelo",9,"peak","", "castle peak","Burggipfel","pic du Château","picco del castello","várhegy-csúcs","burchttop"),
("Ribeira da Metade",9,"stream","", "halfway stream","Bach der Hälfte","torrent de la Moitié","torrente della metà","félút-patak","beek van de helft"),
("Rua do Aljube",9,"street (Funchal)","*aljube* = the bishop's prison.", "bishop's prison street","Straße des Bischofsgefängnisses","rue de la Prison épiscopale","via del carcere vescovile","püspöki börtön utcája","straat van de bisschoppelijke gevangenis"),
("Campo do Duque",9,"square (Funchal)","", "duke's field","Herzogsplatz","champ du Duc","campo del duca","herceg tere","hertogsveld"),
("Quinta das Cruzes",9,"estate/museum (Funchal)","", "estate of the crosses","Landgut der Kreuze","domaine des Croix","tenuta delle croci","keresztek birtoka","landgoed van de kruisen"),
("Ponta do Garajau",8,"cape","*garajau* = tern.", "tern point","Seeschwalbenspitze","pointe de la Sterne","punta della sterna","csér-fok","sternkaap"),
("Ribeira do Inferno",8,"stream","", "hell's stream","Höllenbach","torrent de l'Enfer","torrente dell'inferno","pokol-patak","hellebeek"),
("Água de Mel",8,"locality","", "honey water","Honigwasser","eau de miel","acqua di miele","mézvíz","honingwater"),
("Porto Novo",8,"landing/stream","", "new harbour","neuer Hafen","port neuf","porto nuovo","új kikötő","nieuwe haven"),
("Rocha do Navio",7,"cliff/locality","", "ship cliff","Schiffsfelsen","falaise du Navire","rupe della nave","hajó-sziklafal","scheepsrots"),
("Vale Formoso",7,"locality","", "beautiful valley","schönes Tal","belle vallée","valle bella","szép völgy","mooie vallei"),
("Lombo do Doutor",5,"locality","Owner example; the source names the doctor (Pedro Berenguer de Lemilhana). *lombo* = ridge between two valleys.", "the doctor's ridge","Rücken des Doktors","croupe du Docteur","crinale del dottore","a doktor gerince","rug van de dokter"),
("Homem em Pé",5,"rock","", "standing man","stehender Mann","homme debout","uomo in piedi","álló ember","staande man"),
("Boca dos Namorados",5,"pass","", "lovers' pass","Pass der Liebenden","col des Amoureux","valico degli innamorati","szerelmesek hágója","pas van de geliefden"),
("Caldeirão Verde",4,"valley","", "green cauldron","grüner Kessel","chaudron vert","calderone verde","zöld üst","groene ketel"),
("Nossa Senhora do Monte",30,"parish/sítio","Owner example; Marian toponym (the devotion itself is translated, see dedications table).", "Our Lady of the Mount","Unsere Liebe Frau vom Berge","Notre-Dame du Mont","Madonna del Monte","Monte-i Szűzanya","Onze-Lieve-Vrouw van de Berg"),
]
